import { body, src, type RawSubject } from "./types";

export const javascriptSubject: RawSubject = {
  slug: "javascript",
  title: "JavaScript",
  description:
    "The language of the browser: values, control flow, functions and collections, with runnable examples.",
  icon: "JS",
  colorHex: "#7157ec",
  level: "beginner",
  order: 1,
  modules: [
    {
      slug: "getting-started",
      title: "Getting started",
      description: "Store values, make decisions, repeat work.",
      order: 1,
    },
    {
      slug: "functions-and-data",
      title: "Functions & data",
      description: "Reuse logic and organise information in collections.",
      order: 2,
    },
  ],
  lessons: [
    {
      slug: "values-and-variables",
      title: "Values and variables",
      description:
        "Create containers for data with let and const, and learn how JavaScript labels every value with a type.",
      moduleSlug: "getting-started",
      objectives: [
        "Declare values with let and const and explain when each one is correct",
        "Name the primitive types JavaScript distinguishes",
        "Predict how typeof, + and template literals behave",
      ],
      estimatedMinutes: 8,
      difficulty: "beginner",
      order: 1,
      body: body(
        "A variable is a name you attach to a value so the rest of your program can reach it. Modern JavaScript gives you two keywords for that, and choosing between them is the first habit worth getting right.",
        "## let and const",
        "**const** means the binding cannot be reassigned — use it by default. Reach for **let** only when the value genuinely has to change, such as a counter inside a loop. There is no need for **var** in new code: it is function scoped rather than block scoped, which produces surprises.",
        "Every value has a type and JavaScript works it out at runtime. The primitives are **string**, **number**, **boolean**, **null**, **undefined**, **symbol** and **bigint**. Everything else, including arrays and functions, is an **object**.",
        "## Coercion is where surprises start",
        "The **+** operator is overloaded: if either side is a string it concatenates, otherwise it adds. That is why **\"5\" + 3** is **\"53\"** while **\"5\" - 3** is **2** — subtraction only understands numbers, so the string gets converted. Convert on purpose with **Number(value)** and compare with **===** so nothing is converted silently.",
        "> Prefer const, convert types explicitly, and use === unless you can explain why == is better here.",
        "## Printing values",
        "**console.log()** writes to the developer console. A template literal — a string in backticks with **${expression}** inside — builds text from values without awkward **+** chains.",
      ),
      codeExamples: [
        {
          label: "Declaring and reading values",
          language: "javascript",
          runnable: true,
          code: src(
            "const appName = \"StudyQuest\";",
            "let questionsAnswered = 0;",
            "",
            "questionsAnswered = questionsAnswered + 3;",
            "",
            "console.log(appName, typeof appName);",
            "console.log(questionsAnswered, typeof questionsAnswered);",
            "console.log(`Answered ${questionsAnswered} questions`);",
            "console.log(\"5\" + 3, \"5\" - 3, Number(\"5\") + 3);",
          ),
          explanation:
            "typeof appName is string and typeof questionsAnswered is number. The last line shows that + concatenates while - coerces to a number.",
        },
        {
          label: "Block scope",
          language: "javascript",
          runnable: true,
          code: src(
            "for (let i = 0; i < 3; i += 1) {",
            "  const label = `pass ${i}`;",
            "  console.log(label);",
            "}",
            "",
            "// i and label do not exist out here: they were block scoped.",
          ),
        },
      ],
      related: [
        { label: "Control flow", href: "/subjects/javascript/lessons/control-flow" },
        {
          label: "MDN: grammar and types",
          href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types",
          external: true,
        },
      ],
    },
    {
      slug: "control-flow",
      title: "Control flow",
      description:
        "Branch with if/else, loop over data without off-by-one errors, and keep functions flat.",
      moduleSlug: "getting-started",
      objectives: [
        "Write conditions that test truthiness correctly",
        "Choose between for, for...of and while loops",
        "Use break, continue and early returns",
      ],
      estimatedMinutes: 10,
      difficulty: "beginner",
      order: 2,
      body: body(
        "Programs are mostly decisions plus repetition. JavaScript keeps both readable if your conditions say exactly what you mean.",
        "## Truthiness",
        "A condition is converted to a boolean. Only **false**, **0**, **-0**, **0n**, **\"\"**, **null**, **undefined** and **NaN** are falsy; every other value is truthy — including **[]** and **\"0\"**, which trips people up. Guard missing values with **value ?? fallback** (nullish coalescing, which leaves 0 and \"\" alone) instead of **value || fallback**.",
        "## Loops without off-by-one errors",
        "A **for** loop walking an array should read **i < items.length**, because indexes run from 0 to length - 1. When you do not need the index, **for...of** is shorter and cannot go out of bounds. Use **while** when the stopping condition is not a count.",
        "**break** leaves a loop; **continue** skips to the next round. Inside a function an early **return** usually reads better than nested if blocks.",
        "> Keep conditions positive where possible: **if (isReady)** beats **if (!isNotReady)**.",
      ),
      diagram: {
        title: "How a for loop executes",
        steps: [
          { label: "1 · init", detail: "let i = 0 runs once, before anything else." },
          { label: "2 · test", detail: "i < items.length is checked; false ends the loop." },
          { label: "3 · body", detail: "Statements run; break exits, continue jumps to step 4." },
          { label: "4 · update", detail: "i += 1 runs, then control returns to step 2." },
        ],
        note: "The test happens before the body, so a loop can run zero times.",
      },
      codeExamples: [
        {
          label: "Classify a score",
          language: "javascript",
          runnable: true,
          code: src(
            "function describeScore(percent) {",
            "  if (percent >= 90) return \"excellent\";",
            "  if (percent >= 70) return \"passing\";",
            "  if (percent > 0) return \"needs review\";",
            "  return \"not attempted\";",
            "}",
            "",
            "for (const score of [95, 74, 30, 0]) {",
            "  console.log(score, describeScore(score));",
            "}",
          ),
        },
        {
          label: "Summing with a loop",
          language: "javascript",
          runnable: true,
          code: src(
            "const minutes = [12, 0, 25, 8];",
            "let total = 0;",
            "",
            "for (const value of minutes) {",
            "  if (value === 0) continue;",
            "  total += value;",
            "}",
            "",
            "console.log(total);",
          ),
          explanation: "The zero is skipped, so total is 45.",
        },
      ],
      related: [
        {
          label: "Arrays and objects",
          href: "/subjects/javascript/lessons/arrays-and-objects",
        },
      ],
    },
    {
      slug: "arrays-and-objects",
      title: "Arrays and objects",
      description:
        "Group related values, then transform them with map, filter and reduce instead of hand-written loops.",
      moduleSlug: "functions-and-data",
      objectives: [
        "Read and write object properties with dot and bracket notation",
        "Destructure values and spread collections without mutating the original",
        "Chain map, filter and reduce to describe a transformation",
      ],
      estimatedMinutes: 12,
      difficulty: "beginner",
      order: 1,
      body: body(
        "Once you have more than a handful of values, put them in a collection. An **array** is an ordered list indexed from zero. An **object** is a set of named properties.",
        "## Reading and writing",
        "Use dot notation (**lesson.title**) when the key is a known identifier and bracket notation (**lesson[key]**) when the key is computed. Reading a missing property gives **undefined** instead of an error, so optional chaining (**lesson.quiz?.total ?? 0**) keeps code safe.",
        "## Copying without surprises",
        "Arrays and objects are assigned by reference, so **const b = a** gives you two names for the same value. Spread (**[...a]**, **{...o}**) or **structuredClone()** creates a copy. Prefer copying: functions that mutate their input are harder to reason about.",
        "## Transform instead of loop",
        "**map** returns a new array with one output per input, **filter** returns the items that pass a test, and **reduce** folds the array into a single value. They chain, so the intent reads left to right: take the lessons, keep the finished ones, add up the minutes.",
        "> None of these mutate the original array — that is what makes them safe to reuse.",
      ),
      codeExamples: [
        {
          label: "map / filter / reduce",
          language: "javascript",
          runnable: true,
          code: src(
            "const lessons = [",
            "  { title: \"Values and variables\", minutes: 8, done: true },",
            "  { title: \"Control flow\", minutes: 10, done: true },",
            "  { title: \"Arrays and objects\", minutes: 12, done: false },",
            "];",
            "",
            "const titles = lessons.map((lesson) => lesson.title);",
            "const finished = lessons.filter((lesson) => lesson.done);",
            "const minutes = finished.reduce((total, lesson) => total + lesson.minutes, 0);",
            "",
            "console.log(titles.length, finished.length, minutes);",
          ),
          explanation: "3 lessons, 2 finished, 18 minutes studied.",
        },
        {
          label: "Destructuring and copying",
          language: "javascript",
          runnable: true,
          code: src(
            "const profile = { name: \"Ada\", xp: 240, plan: [\"js\", \"sql\"] };",
            "const { name, xp } = profile;",
            "const plans = [...profile.plan, \"html\"];",
            "",
            "console.log(name, xp, plans.join(\", \"));",
            "console.log(profile.plan.length);",
          ),
          explanation:
            "The spread copied the array, so the original still has 2 entries after plans gains a third.",
        },
      ],
      related: [
        { label: "Control flow", href: "/subjects/javascript/lessons/control-flow" },
        {
          label: "MDN: indexed collections",
          href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections",
          external: true,
        },
      ],
    },
  ],
  questions: [
    {
      kind: "single",
      prompt: "Which keyword should you use when a binding will never be reassigned?",
      options: ["var", "let", "const", "static"],
      answer: 2,
      explanation:
        "const prevents reassignment, which documents intent and removes a class of bugs. var is function scoped; avoid it in new code.",
      difficulty: "beginner",
      lessonSlug: "values-and-variables",
    },
    {
      kind: "code",
      prompt:
        "Fix the last line so the program prints two lines: the number 8, then the sentence Answered 8 questions.",
      answer: "8\nAnswered 8 questions",
      expectedOutput: "8\nAnswered 8 questions",
      starterCode: src(
        "const done = 5;",
        "const skipped = 3;",
        "const total = done + skipped;",
        "",
        "console.log(total);",
        "// Make this line print: Answered 8 questions",
        "console.log(\"Answered \" + \"x\" + \" questions\");",
      ),
      explanation:
        "Interpolate the number with a template literal: console.log(`Answered ${total} questions`). Output comparison ignores letter case and blank lines.",
      hint: "Use backticks and ${total}.",
      points: 3,
      difficulty: "beginner",
      lessonSlug: "values-and-variables",
    },
    {
      kind: "multiple",
      prompt: "Select every value that is falsy in JavaScript.",
      options: ["0", "\"\"", "[]", "null", "\"0\""],
      answer: [0, 1, 3],
      explanation:
        "0, the empty string and null are falsy. An empty array and the string \"0\" are both truthy.",
      difficulty: "intermediate",
      lessonSlug: "control-flow",
    },
    {
      kind: "true_false",
      prompt:
        "For an array of length 4, the loop for (let i = 0; i <= 4; i += 1) visits every element exactly once.",
      answer: false,
      explanation:
        "With <= the body runs 5 times and items[4] is undefined. Use i < items.length.",
      difficulty: "beginner",
      lessonSlug: "control-flow",
    },
    {
      kind: "short_answer",
      prompt: "What does typeof null evaluate to? Answer with the type name only.",
      answer: "object",
      explanation:
        "typeof null is \"object\" — a bug kept for web compatibility. Check explicitly with value === null.",
      difficulty: "intermediate",
      lessonSlug: "values-and-variables",
    },
    {
      kind: "single",
      prompt: "Which expression copies an array so later changes do not affect the original?",
      options: ["const b = a", "const b = [...a]", "const b = a.copy", "const b = a;"],
      answer: 1,
      explanation:
        "Spread creates a new array. It is a shallow copy: nested objects are still shared, so use structuredClone() when you need a deep copy.",
      difficulty: "intermediate",
      lessonSlug: "arrays-and-objects",
    },
    {
      kind: "code",
      prompt:
        "Run the snippet and confirm it prints how many minutes were spent on finished lessons. Expected output: 18",
      answer: "18",
      expectedOutput: "18",
      starterCode: src(
        "const lessons = [",
        "  { minutes: 8, done: true },",
        "  { minutes: 10, done: true },",
        "  { minutes: 12, done: false },",
        "];",
        "",
        "const minutes = lessons",
        "  .filter((lesson) => lesson.done)",
        "  .reduce((total, lesson) => total + lesson.minutes, 0);",
        "",
        "console.log(minutes);",
      ),
      explanation: "The chain keeps the two finished lessons (8 and 10) and folds them into 18.",
      hint: "filter first, then reduce with an initial value of 0.",
      points: 3,
      difficulty: "intermediate",
      lessonSlug: "arrays-and-objects",
    },
  ],
};
